name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Setup GCP Service Account
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
          project_id: '${{ secrets.GCP_PROJECT_ID }}'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: |
            cd terraform
            terraform init

      - name: Terraform Apply
        run: |
            cd terraform
            terraform apply -auto-approve 

      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      - name: Build
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/py-note-cicd:latest .

      - name: Push && Deploy
        run: |
          gcloud run deploy flask-app --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/py-note-cicd:latest --platform managed --region europe-west10 --allow-unauthenticated

